# Train Face Recognition Model

#### Import Libraries

In [6]:
import numpy as np
import cv2
import os
# import the face recognition file we just created that has the classifier in it
import Face_Recognition as fr

#### Give path to the image you want to test the model with

In [7]:
test_img = cv2.imread(r'dataset\test_images\image0000.jpg')

In [8]:
print(test_img)

[[[173 173 167]
  [176 176 170]
  [178 177 173]
  ...
  [100 123  79]
  [ 99 124  80]
  [ 95 122  78]]

 [[173 173 167]
  [175 175 169]
  [176 175 171]
  ...
  [100 120  77]
  [ 98 121  77]
  [ 94 119  75]]

 [[172 172 166]
  [174 174 168]
  [173 174 170]
  ...
  [102 119  76]
  [ 99 119  74]
  [ 96 116  71]]

 ...

 [[104  38  33]
  [106  40  35]
  [113  45  40]
  ...
  [129  61  32]
  [126  59  32]
  [124  57  30]]

 [[104  39  31]
  [104  39  31]
  [110  42  37]
  ...
  [130  62  33]
  [128  59  32]
  [126  57  30]]

 [[101  36  28]
  [101  36  28]
  [107  39  34]
  ...
  [130  62  33]
  [129  60  33]
  [126  57  30]]]


In [9]:
# Feed the model with the test img
faces_detected, gray_img = fr.face_detection(test_img)
print('Face Detected: ', faces_detected)

Face Detected:  [[241  52 209 209]]


#### Train the model 

In [ ]:
faces, faceID = fr.labels_for_training_data(r'dataset\images')
face_recognizer = fr.train_classifier(faces, faceID) # get the classifier and feed it faces with the id so it can correctly recognize
face_recognizer.save('trainingData.yml') # save the model to this location 

img_path dataset\images\0\image0000.jpg
id:  0
img_path dataset\images\0\image0001.jpg
id:  0
img_path dataset\images\0\image0002.jpg
id:  0
img_path dataset\images\0\image0003.jpg
id:  0
img_path dataset\images\0\image0004.jpg
id:  0
img_path dataset\images\0\image0005.jpg
id:  0
img_path dataset\images\0\image0006.jpg
id:  0
img_path dataset\images\0\image0007.jpg
id:  0
img_path dataset\images\0\image0008.jpg
id:  0
img_path dataset\images\0\image0009.jpg
id:  0
img_path dataset\images\0\image0010.jpg
id:  0
img_path dataset\images\0\image0011.jpg
id:  0
img_path dataset\images\0\image0012.jpg
id:  0
img_path dataset\images\0\image0013.jpg
id:  0
img_path dataset\images\0\image0014.jpg
id:  0
img_path dataset\images\0\image0015.jpg
id:  0
img_path dataset\images\0\image0016.jpg
id:  0


In [ ]:
#name = {0:'Thobela', 1: "Bobo"} # zero is the label, so if there are more people write it as a long dictionary
name = {0:'Thobela'}

In [ ]:
for face in faces_detected:
    (x, y, w, h) = face
    roi_gray = gray_img[y:y+w, x: x+h]  # roi means reason of interest, it should be y+w
    label, confidence = face_recognizer.predict(roi_gray) 
    print('Confidence : ', confidence) # confidence is how confident the model is with the recognition
    print('label : ', label)
    fr.draw_rect(test_img, face)
    predicted_name = name[label]
    fr.place_text(test_img, predicted_name, x, y)

In [ ]:
resized_img = cv2.resize(test_img, (1000, 700))

In [ ]:
cv2.imshow("face detection ", resized_img)
cv2.waitKey(0)
cv2.destroyAllWindows()